services:
  app:
    container_name: icls-web
    restart: 'always'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5002:9183
    environment:
      - SECRET_KEY=3ccef32a4991129e86b6f80611a3e1e5287475c27d7ab3a8e26d122862119c49
      - SALT=%2b%12%4/ZiN3Ga8VQjxm9.K2V3/.
    volumes:
      - ../reports:/app/reports
